---
- name: AS2 - Install webserver + deploy homepage
  hosts: web1
  become: true

  vars:
    web_pkgs:
      Debian: apache2
      RedHat: httpd
    web_services:
      Debian: apache2
      RedHat: httpd
    web_roots:
      Debian: /var/www/html
      RedHat: /var/www/html

  tasks:
    - name: Install webserver package (Debian/RedHat)
      ansible.builtin.package:
        name: "{{ web_pkgs[ansible_os_family] }}"
        state: present

    - name: Ensure web service is enabled + running
      ansible.builtin.service:
        name: "{{ web_services[ansible_os_family] }}"
        state: started
        enabled: true

    - name: Deploy custom index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ web_roots[ansible_os_family] }}/index.html"
        owner: root
        group: root
        mode: "0644"
      notify: Restart web service

  handlers:
    - name: Restart web service
      ansible.builtin.service:
        name: "{{ web_services[ansible_os_family] }}"
        state: restarted
